# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default YOLO tracker settings for BoT-SORT tracker https://github.com/NirAharon/BoT-SORT

tracker_type: botsort  # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.4  # threshold for the first association 0.5
track_low_thresh: 0.1  # threshold for the second association 0.1
new_track_thresh: 0.10  # threshold for init new track if the detection does not match any tracks 0.6, se è più basso prende persona seduta
track_buffer: 300 # buffer to calculate the time when to remove tracks 30
match_thresh: 0.8  # threshold for matching tracks 0.8
alpha: 0.9 #0.9
non_maximum_iou_distance: 0.15 #0.15
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)
# mot20: False  # for tracker evaluation(not used for now)

# BoT-SORT settings
gmc_method: sparseOptFlow  # method of global motion compensation
# ReID model related thresh (not supported yet)
proximity_thresh: 0.5 #0.5
appearance_thresh: 0.25 #0.25
with_reid: False #false