#Verbose during prediction
verbose: False

img_size: 640
epochs: 200
batch_size: 16

# for training
mode: 'train' # 'train' or 'train resume'
data: "./datasets/CrowdHuman/yolo/dataset.yaml"
output: "yolov8n_crowdhuman"
model: yolov8n.pt
resume: False
#model: "runs/detect/yolov8s_crowdhuman/weights/best.pt"

