#Verbose during prediction
verbose: False

img_size: 640
epochs: 50
batch_size: 16

# for training
# Cross-validation parameters
cross_val:
  ksplit: 5  # Change this value as needed
  random_state: 20  # Change this value as needed 

mode: 'train'
data: ".\\datasets\\all_data\\dataset.yaml"
dataset_path: ".\\datasets\\all_data\\"
output: "yolov8n_mot_ch"
model: weights/yolov8n.pt
resume: False